name=Embedded GUI Framework
version=1.0.0
author=Cordell O'Leary (cordelloleary@gmail.com)
maintainer=Cordell O'Leary (cordelloleary@gmail.com)
sentence=A simple framework to create GUIs with Adafruit GFX displays.
paragraph=This will allow you to create GUIs on displays supported by the adafruit gfx library
category=Display
url=https://github.com/CDonalO/Embedded-GUI-Framework
architectures=*
depends=Adafruit GFX Library